# Generated by Django 4.0.5 on 2022-06-18 13:27

from django.db import migrations, models
import validation


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=500, null=True, validators=[validation.validate_password]),
        ),
    ]
